'use strict';

module.exports = {
  WINDOW_WIDTH: 640,
  WINDOW_HEIGHT: 480,

  NUM_VEHICLES: 100,
  VEHICLE_COLOR: 'rgba(0,0,0,1)',
  VEHICLE_MIN_SPEED: 1,
  VEHICLE_MAX_SPEED: 3,
  VEHICLE_MAX_TURN: 0.1, // radians
  VEHICLE_SIZE: 6,
  VEHICLE_THICKNESS: 2,
  MAX_BOREDOM: 5000,

  BACKGROUND_COLOR: '#fff',
  TRAILS_COLOR: 'rgba(0,0,0,0.01 )',
};
