'use strict';

module.exports = {
  WINDOW_WIDTH: 640,
  WINDOW_HEIGHT: 480,

  VEHICLE_COLOR: 'rgba(0,0,0,1)',
  VEHICLE_MIN_SPEED: 0.2,
  VEHICLE_MAX_SPEED: 10,
  VEHICLE_MAX_TURN: 20,
  VEHICLE_SIZE: 6,
  VEHICLE_THICKNESS: 2,

  BACKGROUND_COLOR: '#fff',
  TRAILS_COLOR: 'rgba(0,0,0,0.002)',
};
